[package]
name = "ayagami-ffi"
version = "0.2.0"
edition = "2021"
license = "MIT"

[lib]
name = "ayagami_ffi"
crate-type = ["staticlib"]

[dependencies]
ayagami = { git = "https://github.com/AyagamiDev/ayagami", rev = "0d1d7aa3efe57b1b363b72e672e353c52a9c15d6" }
serde_json = "1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
